# Use travis docker infrastructure
sudo: required
language: cpp

env:
    global:
        - PREFIX=$HOME/prefix

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository --yes ppa:smspillaz/cmake-2.8.12 # Non official cmake backport
    - sudo apt-get update -qq

install:
    - sudo apt-get install --yes swig cmake cmake-data valgrind g++-4.8 python3-dev libasio-dev
    - sudo pip install cpp-coveralls
    - wget --directory-prefix $PREFIX/include
              https://raw.github.com/philsquared/Catch/master/single_include/catch.hpp
    - wget 'https://01.org/sites/default/files/asio-1.10.6.tar.gz'
    - tar xf asio-1.10.6.tar.gz -C $PREFIX --strip-components=1

before_script:
    - if [ "$CC" = "gcc" ]; then export CC=gcc-4.8 CXX=g++-4.8; fi

# how to build
script:
  - ( mkdir build_debug && cd build_debug &&
        cmake -DCMAKE_PREFIX_PATH=$PREFIX -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON .. &&
        make -j &&
        CTEST_OUTPUT_ON_FAILURE=1 make ExperimentalTest ExperimentalMemCheck )
  - ( mkdir build && cd build &&
        cmake -DCMAKE_PREFIX_PATH=$PREFIX -DCMAKE_INSTALL_PREFIX=../install .. &&
        make -j &&
        CTEST_OUTPUT_ON_FAILURE=1 make test &&
        make install)
  - ( cd skeleton-subsystem &&
        cmake -DCMAKE_INSTALL_PREFIX=../install . &&
        make &&
        make install )
  - ( cd tools/clientSimulator &&
        cmake -DCMAKE_INSTALL_PREFIX=../install . &&
        make &&
        make install )

after_success:
    # Push coverage info on coveralls.io.
    # Ignore generated files, samples and tests
    - coveralls
          --exclude "build_debug/bindings/python"
          --exclude "build_debug/CMakeFiles"
          --exclude "build"
          --exclude "install"
          --exclude "skeleton-subsystem"
          --exclude "tools/clientSimulator"
          --exclude "test/test-subsystem"
          --exclude "test/functional-tests"
          --exclude "bindings/c/Test.cpp"
          --exclude "test/tokenizer"
          --gcov /usr/bin/gcov-4.8
          --gcov-options '\--long-file-names --preserve-paths'

notifications:
  irc:
    - "chat.freenode.net#parameter-framework"
